version: '3.8'
services:
  db:
    image: postgres:14
    container_name: makers-tech-db
    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

